# Generated by Django 5.1.6 on 2025-02-16 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('likes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_profile', to='user_profile.userprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_profile', to='user_profile.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'likes')},
            },
        ),
    ]
