# Generated by Django 4.2.7 on 2025-02-14 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_auto_20180909_2124'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
